### ISSUE TITLE
HfDeepSpeedConfig must be kept during AutoModel.from_pretrained if using ZeRO-3

### ISSUE THREAD

**Issue by wuxibin89** [OpenLLMAI/OpenLLaMA2#100]
According to [Non-Trainer Deepspeed Integration](https://huggingface.co/docs/transformers/main_classes/deepspeed#nontrainer-deepspeed-integration):
> The [HfDeepSpeedConfig](https://huggingface.co/docs/transformers/v4.33.0/en/main_classes/deepspeed#transformers.integrations.HfDeepSpeedConfig) is used to integrate Deepspeed into the 🤗 Transformers core functionality, when [Trainer](https://huggingface.co/docs/transformers/v4.33.0/en/main_classes/trainer#transformers.Trainer) is not used. The only thing that it does is handling Deepspeed ZeRO-3 param gathering and automatically splitting the model onto multiple gpus during from_pretrained call.
```python
from transformers.integrations import HfDeepSpeedConfig
from transformers import AutoModel
import deepspeed

ds_config = {...}  # deepspeed config object or path to the file
# must run before instantiating the model to detect zero 3
dschf = HfDeepSpeedConfig(ds_config)  # keep this object alive
model = AutoModel.from_pretrained("gpt2")
engine = deepspeed.initialize(model=model, config_params=ds_config, ...)
```
But we seem to missing HfDeepSpeedConfig when init [Actor](https://github.com/OpenLLMAI/OpenLLaMA2/blob/main/openllama2/models/actor.py#L30-L39), [Critic](https://github.com/OpenLLMAI/OpenLLaMA2/blob/main/openllama2/models/critic.py#L22-L29), [Reward](https://github.com/OpenLLMAI/OpenLLaMA2/blob/main/openllama2/models/reward_model.py#L22-L29).

**Comment by hijkzzz** [comment]
this feature is used for ZeRO3 + save init GPU memory. Our RLHF only use ZeRO2 now~
