### ISSUE TITLE
Bug: AttributeError: 'DeepspeedStrategy' object has no attribute 'save_hf_format'

### ISSUE THREAD

**Issue by catqaq** [OpenLLMAI/OpenLLaMA2#101]
when use --save_hf_model:
I got a training collapse when saving models. so, 30 hours wasted.

strategy.save_hf_format(model, tokenizer, args.save_path + '/sft_hf')
AttributeError: 'DeepspeedStrategy' object has no attribute 'save_hf_format'

At last, only a 67k sft_model.pt was saved.

**Comment by hijkzzz** [comment]
I will try to fix this. the checkpoint feature is somewhat complex, i will develop it after i finished the ray feature.

**Comment by hijkzzz** [comment]
fixed
