### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by skepsun** [OpenLLMAI/OpenLLaMA2#91]
1. 为什么使用.pt文件保存模型，而不是直接save_pretrained保存成hf格式？如果我需要将其他框架训练得到的hf格式的sft模型用于rm和ppo的话，我只能自己修改代码支持hf格式ckpt的读取。
2. prompt template可以多定义几个，比如常见的alpaca、vicuna和llama2格式。
3. rm和ppo的日志输出有点看不明白，比如rm的acc在哪，ppo的mean reward是哪个量，例如：
```
Train epoch [1/1]: 100%|█| 146/146 [09:37<00:00,  3.95s/it, pg=0.511, cri=0.0207, vals=0
{'pg': -0.007849020959988032, 'cri': 0.009956638121416103, 'vals': 0.28283763604481027, 'kl': -0.0015669609786402971, 'rm': 0.380661175522494, 'ret': 0.3954394154046496, 'glen': 942.7006952991225, 'tlen': 1071.2466288527398, 'k_coef': 0.01}
```
这里面的vals，rm和ret分别代表什么含义？

**Comment by hijkzzz** [comment]
1. 因为 save_pretrained 在分布式场景下不好用，模型分片后无法使用
但是我们支持save_hf格式，可以用选项 
parser.add_argument('--save_hf_model', action='store_true', default=False)

2. 可以的 后面加一下
3. 为了一行放得下去所以
vals  = values
rm = rewards
cri = critic loss
pg = policy loss 
glen = generate length
tlen = total length

**Comment by skepsun** [comment]
好的！感谢回复！
