### ISSUE TITLE
Do you have a plan for applying Reinforced Self-Training (ReST)?

### ISSUE THREAD

**Issue by missflash** [OpenLLMAI/OpenLLaMA2#97]
Thansks for sharing a great project!

Do you have any plans to apply the recently published Reinforced Self-Training (ReST)?

Reinforced Self-Training (ReST) for Language Modeling
https://arxiv.org/abs/2308.08998

**Comment by hijkzzz** [comment]
Yes, openllama2 will support a lot of alignment algorithms.  You can also contribute ReST to openllama2 if you are interested in it~
